
stages:
  # always_run:
  #   cmd: python rough/test.py
  #   #out: of this stage can be track with any other stage 
  #   # where its needed, To keep this process running its necessary to do this.


  load_data:
    cmd: python src/stage_01_load_save.py  --config=config/config.yaml
    deps:
      - src/stage_01_load_save.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - artifacts/raw_local_dir/data.csv

  split_data:
    cmd: python src/stage_02_split_data.py  --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_02_split_data.py
      - src/utils/all_utils.py
      - config/config.yaml

    # as we are tracking params so do not need to track params.yaml
    params:
      - base.random_state
      - base.test_size
    outs:
      - artifacts/split_data_dir/train.csv
      - artifacts/split_data_dir/test.csv






